definition: definition.json
name: Kenku Sales Bot
slug: kenku-sales-bot
status: active
triggers:
  - active: true
    phoneNumberId: "1145171692021464"
    triggerType: inbound_message
  - active: true
    phoneNumberId: "1239315459260256"
    triggerType: inbound_message
  - active: true
    phoneNumberId: "597907523413541"
    triggerType: inbound_message
